Algoritmo "semnome"
// Desenvolver um programa que apresente o fatorial de um número qualquer.
Var
// Seção de Declarações das variáveis 
cont, num, multi : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Escolha um número: ")
   leia(num)
   
   multi <- 1
   
   para cont de 1 ate num passo 1 faca
        multi <- cont * multi
        
   fimpara
   
   escreval(multi)



Fimalgoritmo