Algoritmo "semnome"
//Desenvolver um programa que apresente no final a soma dos valores pares
//existentes na faixa de 3 até 21.
Var
   // Seção de Declarações das variáveis
   cont : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...



   para cont de 3 ate 21 passo 1 faca
      se ( cont % 2 = 0 ) entao
         escreval(cont)


      fimse
      fimpara



Fimalgoritmo