Algoritmo "semnome"
//Desenvolver um programa que apresente os resultados de uma tabuada de
//um número qualquer.
Var
   // Seção de Declarações das variáveis
   multi, num, cont : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Escolha um número: ")
   leia(num)

   para cont de 0 ate 10 passo 1 faca

      multi <- cont * num

      escreval( multi )

   fimpara





Fimalgoritmo